# reload tmux configs =========================================================
unbind C-r
bind C-r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# kill pane without confirmation ==============================================
bind -r C-x kill-pane

# put the status bar at the top ===============================================
set-option -g status-position top

# resize pane =================================================================
bind -r C-h resize-pane -L 1
bind -r C-j resize-pane -D 1
bind -r C-k resize-pane -U 1
bind -r C-l resize-pane -R 1

# navigate splits =============================================================
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n M-h  if-shell  "$is_vim"  "send-keys M-h"  "select-pane -L"
bind-key -n M-j   if-shell  "$is_vim"  "send-keys M-j"   "select-pane -D"
bind-key -n M-k  if-shell  "$is_vim"  "send-keys M-k"  "select-pane -U"
bind-key -n M-l   if-shell  "$is_vim"  "send-keys M-l"   "select-pane -R"
bind-key -n M-\   if-shell  "$is_vim"  "send-keys M-\\"  "select-pane -l"

# enable copy and paste =======================================================
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -sel clip > /dev/null"
bind p run "xclip -o -sel clip | tmux load-buffer - ; tmux paste-buffer"

# create splits in PWD with Vim equivalent keys ===============================
bind -r v split-window -h -p 50 -c '#{pane_current_path}' # horizontally split active pane
bind -r s split-window -v -p 50 -c '#{pane_current_path}' # vertically split active pane

# plugin: tpm =================================================================
# prefix + I - installs new plugins and refreshes tmux env
# prefix + U - updates plugins
# the plugin manager
set -g @plugin 'tmux-plugins/tpm'

# plugin: tmux-sensible =======================================================
# sensible defaults for tmux:
#   set -s escape-time 0
#   bind C-p previous-window
#   bind C-n next-window
#   some other ones (see github page)
set -g @plugin 'tmux-plugins/tmux-sensible'

# plugin: tmux-resurrect ======================================================
# persists tmux env across system restarts
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @resurrect-strategy-nvim 'session'

# plugin: tmux-continuum ======================================================
# makes tmux-resurrect save/restore automatic
set -g @plugin 'tmux-plugins/tmux-continuum'

# initialize plugin manager (keep this line at the very bottom of the file) ===
run -b '~/.tmux/plugins/tpm/tpm'

