#!/usr/bin/env sh

xsetroot -cursor_name left_ptr  # Set default cursor to pointer
setbg &                         # Set the background
pkill sxhkd                     # Ensure only one instance running
sxhkd &                         # Bind keys
xset s 600 600                  # Monitor sleep after 10 mins
xset r rate 175 50              # Speed xrate up [delay] [rate]
dunst &                         # dunst for notifications
clipmenud &                     # Clipmenu for accessing copy history

# Adjust mouse sensitivity
DeathAdder=`xinput list |grep -i "Razer Razer DeathAdder 2013" | awk -F= '{ print $2}'| awk '{print $1}'| awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`
Touchpad=`xinput list |grep -i "Touchpad" | awk -F= '{ print $2}'| awk '{print $1}'| awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`
xinput set-prop $DeathAdder "Coordinate Transformation Matrix" .6 0 0 0 .6 0 0 0 1
xinput set-prop $Touchpad "Coordinate Transformation Matrix" 2 0 0 0 2 0 0 0 1
