return {
    "airblade/vim-gitgutter",
    "dhruvasagar/vim-table-mode",
    "fatih/vim-go",
    "gleam-lang/gleam.vim",
    "google/vim-searchindex",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-nvim-lsp",
    "machakann/vim-highlightedyank",
    "mbbill/undotree",
    "olimorris/onedarkpro.nvim",
    "rust-lang/rust.vim",
    "sainnhe/everforest",
    "SirVer/ultisnips",
    "tpope/vim-commentary",
    "tpope/vim-repeat",
    "tpope/vim-surround",
    "vim-airline/vim-airline",
    "vim-airline/vim-airline-themes",
    "vim-scripts/ReplaceWithRegister",
    { "catppuccin/nvim", name = "catppuccin" },
    { "junegunn/fzf", build = "./install --all" },
    { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
}

